### ISSUE TITLE
🐛 [Bug Report] Quest 10277 crashes server if u go far away from quest-npc

### ISSUE THREAD

**Issue by ykslol** [cmangos/issues#2146]
## 🐛 Bugreport
Quest in [The Caverns of Time](https://www.wowhead.com/quest=10277/the-caverns-of-time) crashes server get segrault if u go far away from npc which shows to u caverns of time

### Expected behavior
Server must not be crashed. 
May be quest sould be failed.

### Version & Environment
 -  [Commit Hash](https://github.com/cmangos/mangos-tbc/tree/e5d065)
 - [Database Version](https://github.com/cmangos/tbc-db/tree/320eb)
 - Boost: 1.62.0 
 - OpenSSL: 1.1.0l  
 - Revision time stamp   : "2020-01-12T02:38:02+03:00"
 - gcc (GCC) 7.3.0
 - mysql  Ver 15.1 Distrib 10.1.44-MariaDB, using readline 5.2
 - build line:
       /usr/local/cmake/bin/cmake ../../ \
           -DCMAKE_INSTALL_PREFIX=/server \
           -DBUILD_GAME_SERVER=1 \
           -DBUILD_LOGIN_SERVER=0 \
           -DBUILD_EXTRACTORS=0 \
           -DPCH=0 \
           -DBUILD_PLAYERBOT=0 \
           -DDEBUG=1 \

- Client version: "2.4.3" (TBC)
- runing under docker image ubuntu:18.04 - kernel 4.4.0-174-generic
### Steps to reproduce
1. Get 64 lvl (minimum) - i do this on 70
2. Go Tanaris and do first quest -  [to-the-masters-lair](https://www.wowhead.com/quest=10279/to-the-masters-lair) 
3. Get second quest [The Caverns of Time](https://www.wowhead.com/quest=10277/the-caverns-of-time)
4. While quest-NPC will show to u Caverns of Time go far away from it
5. Crash

- NOTE: If u be near the quest-npc - quest will be done without problems.

### Crashlog
```
Core was generated by `/opt/mangos/bin/mangosd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000da3ef2 in Quest::GetQuestId (this=0x0) at /core/src/game/Quests/QuestDef.h:198
198	/core/src/game/Quests/QuestDef.h: No such file or directory.
[Current thread is 1 (Thread 0x7f80c53d6700 (LWP 18))]
(gdb) bt
#0  0x0000000000da3ef2 in Quest::GetQuestId (this=0x0) at /core/src/game/Quests/QuestDef.h:198
#1  0x00000000015190fd in npc_escortAI::FailQuestForPlayerAndGroup (this=0x7f8098b168a0) at /core/src/game/AI/ScriptDevAI/base/escort_ai.cpp:104
#2  0x000000000151932b in npc_escortAI::UpdateAI (this=0x7f8098b168a0, diff=100) at /core/src/game/AI/ScriptDevAI/base/escort_ai.cpp:147
#3  0x0000000000f252dc in Unit::Update (this=0x7f80b7f3a060, diff=100) at /core/src/game/Entities/Unit.cpp:478
#4  0x0000000000e264ce in Creature::Update (this=0x7f80b7f3a060, diff=100) at /core/src/game/Entities/Creature.cpp:703
#5  0x0000000000f19cfa in TemporarySpawn::Update (this=0x7f80b7f3a060, diff=100) at /core/src/game/Entities/TemporarySpawn.cpp:214
#6  0x000000000106cd65 in Map::Update (this=0x17263df0, t_diff=@0x7f80b5803f98: 100) at /core/src/game/Maps/Map.cpp:683
#7  0x00000000010894ba in MapUpdateWorker::execute (this=0x7f80b5803f80) at /core/src/game/Maps/MapWorkers.h:51
#8  0x000000000109e6c4 in MapUpdater::WorkerThread (this=0x17168800) at /core/src/game/Maps/MapUpdater.cpp:96
#9  0x000000000109efd6 in std::__invoke_impl<void, void (MapUpdater::*)(), MapUpdater*> (
    __f=@0x17167390: (void (MapUpdater::*)(MapUpdater * const)) 0x109e666 <MapUpdater::WorkerThread()>, __t=@0x17167388: 0x17168800)
    at /usr/local/include/c++/7.3.0/bits/invoke.h:73
#10 0x000000000109e8d1 in std::__invoke<void (MapUpdater::*)(), MapUpdater*> (
    __fn=@0x17167390: (void (MapUpdater::*)(MapUpdater * const)) 0x109e666 <MapUpdater::WorkerThread()>, __args#0=@0x17167388: 0x17168800)
    at /usr/local/include/c++/7.3.0/bits/invoke.h:95
#11 0x00000000010a04dd in std::thread::_Invoker<std::tuple<void (MapUpdater::*)(), MapUpdater*> >::_M_invoke<0ul, 1ul> (this=0x17167388)
    at /usr/local/include/c++/7.3.0/thread:234
#12 0x00000000010a0493 in std::thread::_Invoker<std::tuple<void (MapUpdater::*)(), MapUpdater*> >::operator() (this=0x17167388)
    at /usr/local/include/c++/7.3.0/thread:243
#13 0x00000000010a0472 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (MapUpdater::*)(), MapUpdater*> > >::_M_run (this=0x17167380)
    at /usr/local/include/c++/7.3.0/thread:186
#14 0x00007f80d74806ef in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007f80d88af6db in start_thread (arg=0x7f80c53d6700) at pthread_create.c:463
#16 0x00007f80d6b3d88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
- Also i have core-dump file an online stand where u can check this.

**Comment by Booggmz** [comment]
got in in debian:stretch with latest build (today, now) and gdb
[log2020-03-13-19-11-37.log](https://github.com/cmangos/issues/files/4331357/log2020-03-13-19-11-37.log)

**Comment by cyberium** [comment]
Server not crashing now, but i think there is something missing because it doesn't set the quest to fail state.

**Comment by MantisLord** [comment]
> Server must not be crashed. May be quest should be failed.

> Server not crashing now, but i think there is something missing because it doesn't set the quest to fail state.

On retail you're allowed to be quite far away from the Custodian of Time and the quest does not fail like a regular escort.
You actually don't have to follow her at all. You can just accept the quest and sit AFK at Andormu. She'll loop all the way around the Caverns and you'll still complete the quest. People mention this a lot in the comments about the quest here for example: https://www.wowhead.com/quest=10277/the-caverns-of-time#comments:id=110220

So if there's no more crash happening, I think we can safely close this.
