### ISSUE TITLE
🐛 [Bug Report] Bots crashes core due to pathing (most likely)

### ISSUE THREAD

**Issue by Mr-Deadbeat** [cmangos/issues#2186]
## 🐛 Bugreport Bots crash core when getting stuck in pathing (most likely)

Bot crashes core most likely due to getting stuck in pathing inside the druid trainers tree in Darnassus

### Expected behavior
no crash

### Version & Environment
OS Ubuntu 18.04.4 64bit Server

Client Version: 
 "2.4.3" (TBC)

CMaNGOS Repo & Commit Hash: 

[TBC](https://github.com/cmangos/mangos-tbc/tree/6d13dd4834bc29a9fb40bd10a6db1faec36be3aa)

Database Repo & Commit Hash: 

[TBC](https://github.com/cmangos/tbc-db/tree/969ce46f9ed35cc1da772b8c165213f3b4bcb2bb)

Operating System: 

Linux Flavor

### Steps to reproduce

summon a bot and walk up and down that tree use follow auto to get some distance to the bot
and the server should segfault i have reproduced the crash multiple times on my server

### Crashlog

``` Thread 10 "mangosd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe4b94700 (LWP 3590)]
0x000055555600e2f7 in FreezeDetectorRunnable::run (this=0x55556ba574e0)
    at /home/gameadm/source/mangosbc/src/mangosd/Master.cpp:93
93	                    *((uint32 volatile*)nullptr) = 0;          // bang crash

info threads
  Id   Target Id         Frame 
  1    Thread 0x7ffff7fe0740 (LWP 3549) "mangosd" 0x00007ffff7bc7c60 in __GI___nanosleep (requested_time=0x7fffffffe030, remaining=0x7fffffffe030)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  2    Thread 0x7ffff5b42700 (LWP 3553) "mangosd" 0x00007ffff7bc7c60 in __GI___nanosleep (requested_time=0x7ffff5b41d10, remaining=0x7ffff5b41d10)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  3    Thread 0x7ffff5341700 (LWP 3554) "mangosd" 0x00007ffff7bc7c60 in __GI___nanosleep (requested_time=0x7ffff5340d10, remaining=0x7ffff5340d10)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  4    Thread 0x7ffff4b40700 (LWP 3555) "mangosd" 0x00007ffff7bc7c60 in __GI___nanosleep (requested_time=0x7ffff4b3fd10, remaining=0x7ffff4b3fd10)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  8    Thread 0x7fffdd844700 (LWP 3588) "mangosd" dtNavMeshQuery::getPathToNode
    (this=0x7fffd03b4b10, endNode=0x7fffd03b4f80, path=0x7fffb92a5538, 
    pathCount=0x7fffdd84380c, maxPath=58)
    at /home/gameadm/source/mangosbc/dep/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp:1209
  9    Thread 0x7fffe4393700 (LWP 3589) "mangosd" 0x00007ffff7bc39f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55556add62a4)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
* 10   Thread 0x7fffe4b94700 (LWP 3590) "mangosd" 0x000055555600e2f7 in FreezeDetectorRunnable::run (this=0x55556ba574e0)
---Type <return> to continue, or q <return> to quit---
at /home/gameadm/source/mangosbc/src/mangosd/Master.cpp:93
  11   Thread 0x7fffce458700 (LWP 3591) "mangosd" 0x00007ffff6307bb7 in epoll_wait (epfd=22, events=0x7fffce457640, maxevents=128, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  12   Thread 0x7fffcdc57700 (LWP 3592) "mangosd" 0x00007ffff6307bb7 in epoll_wait (epfd=18, events=0x7fffcdc56630, maxevents=128, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  13   Thread 0x7fffcd456700 (LWP 3593) "mangosd" 0x00007ffff6307bb7 in epoll_wait (epfd=29, events=0x7fffcd455640, maxevents=128, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  14   Thread 0x7fffccc55700 (LWP 3594) "mangosd" 0x00007ffff6307bb7 in epoll_wait (epfd=25, events=0x7fffccc54630, maxevents=128, timeout=-1)
    at ../sysdeps/unix/sysv/linux/epoll_wait.c:30

#0  0x000055555600e2f7 in FreezeDetectorRunnable::run (this=0x55556ba574e0)
    at /home/gameadm/source/mangosbc/src/mangosd/Master.cpp:93
#1  0x000055555605c74d in MaNGOS::Thread::ThreadTask (param=0x55556ba574e0)
    at /home/gameadm/source/mangosbc/src/shared/Threading.cpp:84
#2  0x000055555605ce9f in std::__invoke_impl<void, void (*)(void*), void*> (
    __f=@0x55556ba55500: 0x55555605c722 <MaNGOS::Thread::ThreadTask(void*)>)
    at /usr/include/c++/7/bits/invoke.h:60
#3  0x000055555605cb90 in std::__invoke<void (*)(void*), void*> (
    __fn=@0x55556ba55500: 0x55555605c722 <MaNGOS::Thread::ThreadTask(void*)>)
    at /usr/include/c++/7/bits/invoke.h:95
#4  0x000055555605d155 in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::_M_invoke<0ul, 1ul> (this=0x55556ba554f8)
    at /usr/include/c++/7/thread:234
#5  0x000055555605d0f6 in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::operator() (this=0x55556ba554f8) at /usr/include/c++/7/thread:243
#6  0x000055555605d0c6 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(void*), void*> > >::_M_run (this=0x55556ba554f0)
    at /usr/include/c++/7/thread:186
#7  0x00007ffff6c4a6df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7bbd6db in start_thread (arg=0x7fffe4b94700)
    at pthread_create.c:463
#9  0x00007ffff630788f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95 ```

**Comment by cala** [comment]
Looks more related to pathing than to bots. Could you try to replicate this with a player auto-following you instead of being followed by a bot, please ? Create a second player account and launch a second instance of wow.exe to do so.

**Comment by berserkingyadis** [comment]
HB and me recorded the crash. He had a playerbot following him, ran up the stairs and the bot suddenly ran to the right and the server crashed.

https://www.youtube.com/watch?v=7aE75Ky-loU

We retried the same scenario with me following him but the server didnt crash, my char followed him up the stairs (and eventually fell through the middle but I think thats just the terrain lol)

@cala

**Comment by cala** [comment]
👍

**Comment by cala** [comment]
Important updates on this issue.

After several tests it appears that:
- the issue is unrelated to nearby NPCs as the crash still occurs when removing them
- the issue appears on TBC and WotLK cores but not on Classic core (at least, I did not manage to reproduce it)
- in the case of @Mr-Deadbeat config, this is almost an instant crash. When reproducing it on my config, the server freezes indefinitely instead
- disabling the MMAPS prevents the crash/freeze from occurring

**Comment by cala** [comment]
I have updated tags and title for the issue accordingly.

**Comment by Mr-Deadbeat** [comment]
ok sounds like it will be hard as hell to track it down disabling mmaps is that even an option isn't that fairly important of the operation of the server ? can't say i remember exactly what it was used for though would need to look it up

**Comment by cala** [comment]
MMAPS are used to define paths for moving objects controlled by the server, making them follow terrain or avoid obstacles. If they are disabled, monsters will be able to run through some walls or move through a hill instead of climbing one side and descending on the other side, for examples.

**Comment by Mr-Deadbeat** [comment]
yeah thats what i thought hmm that would make it very interesting doing instances for instance lol monsters rushing you trough a wall ;)

**Comment by Mr-Deadbeat** [comment]
crash in Wetlands by the second small wooden bridge between Menethil harbor and rhelgars excavation it sure looks like it's related same type of info thread and bt take a look
```World Thread hangs, kicking out server!

Thread 13 "mangosd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcd456700 (LWP 3780)]
0x000055555600dfc7 in FreezeDetectorRunnable::run (this=0x55556ba14ad0) at /home/jari/source/mangosbc/src/mangosd/Master.cpp:93
93	                    *((uint32 volatile*)nullptr) = 0;          // bang crash
(gdb) info threads
  Id   Target Id         Frame 
  1    Thread 0x7ffff7fc8740 (LWP 3756) "mangosd" 0x00007ffff7bc7c60 in __GI___nanosleep (requested_time=0x7fffffffdb20, remaining=0x7fffffffdb20) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  2    Thread 0x7ffff5b42700 (LWP 3760) "mangosd" 0x00007ffff7bc7c60 in __GI___nanosleep (requested_time=0x7ffff5b41d10, remaining=0x7ffff5b41d10) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  3    Thread 0x7ffff5341700 (LWP 3761) "mangosd" 0x00007ffff7bc7c60 in __GI___nanosleep (requested_time=0x7ffff5340d10, remaining=0x7ffff5340d10) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  4    Thread 0x7ffff4b40700 (LWP 3762) "mangosd" 0x00007ffff7bc7c60 in __GI___nanosleep (requested_time=0x7ffff4b3fd10, remaining=0x7ffff4b3fd10) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  8    Thread 0x7fffdd844700 (LWP 3775) "mangosd" 0x00007ffff7bc39f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55556adb9fd0) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  9    Thread 0x7fffe4393700 (LWP 3776) "mangosd" 0x00005555569e6027 in dtNavMeshQuery::getPathToNode (this=0x7fffd8616d80, endNode=0x7fffd8618fe0, path=0x7fffb8027358, pathCount=0x7fffe439280c, maxPath=66)
    at /home/jari/source/mangosbc/dep/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp:1213
  10   Thread 0x7fffe4b94700 (LWP 3777) "mangosd" 0x00007ffff7bc39f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55556adb9fd0) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  11   Thread 0x7fffce458700 (LWP 3778) "mangosd" 0x00007ffff7bc39f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55556adb9fd4) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  12   Thread 0x7fffcdc57700 (LWP 3779) "mangosd" 0x00007ffff7bc39f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55556adba050) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
* 13   Thread 0x7fffcd456700 (LWP 3780) "mangosd" 0x000055555600dfc7 in FreezeDetectorRunnable::run (this=0x55556ba14ad0) at /home/jari/source/mangosbc/src/mangosd/Master.cpp:93
  14   Thread 0x7fffccc55700 (LWP 3781) "mangosd" 0x00007ffff6307bb7 in epoll_wait (epfd=22, events=0x7fffccc54640, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  15   Thread 0x7fffc7fff700 (LWP 3782) "mangosd" 0x00007ffff6307bb7 in epoll_wait (epfd=18, events=0x7fffc7ffe630, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  16   Thread 0x7fffc77fe700 (LWP 3783) "mangosd" 0x00007ffff6307bb7 in epoll_wait (epfd=29, events=0x7fffc77fd640, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
  17   Thread 0x7fffc6ffd700 (LWP 3784) "mangosd" 0x00007ffff6307bb7 in epoll_wait (epfd=25, events=0x7fffc6ffc630, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
(gdb) bt
#0  0x000055555600dfc7 in FreezeDetectorRunnable::run (this=0x55556ba14ad0) at /home/jari/source/mangosbc/src/mangosd/Master.cpp:93
#1  0x000055555605b2bd in MaNGOS::Thread::ThreadTask (param=0x55556ba14ad0) at /home/jari/source/mangosbc/src/shared/Threading.cpp:84
#2  0x000055555605b849 in std::__invoke_impl<void, void (*)(void*), void*> (__f=@0x55556ba12c30: 0x55555605b292 <MaNGOS::Thread::ThreadTask(void*)>) at /usr/include/c++/7/bits/invoke.h:60
#3  0x000055555605b53a in std::__invoke<void (*)(void*), void*> (__fn=@0x55556ba12c30: 0x55555605b292 <MaNGOS::Thread::ThreadTask(void*)>) at /usr/include/c++/7/bits/invoke.h:95
#4  0x000055555605baff in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::_M_invoke<0ul, 1ul> (this=0x55556ba12c28) at /usr/include/c++/7/thread:234
#5  0x000055555605baa0 in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::operator() (this=0x55556ba12c28) at /usr/include/c++/7/thread:243
#6  0x000055555605ba70 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(void*), void*> > >::_M_run (this=0x55556ba12c20) at /usr/include/c++/7/thread:186
#7  0x00007ffff6c4a6df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7bbd6db in start_thread (arg=0x7fffcd456700) at pthread_create.c:463
#9  0x00007ffff630788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)```

**Comment by D3thw0lf** [comment]
> I have updated tags and title for the issue accordingly. I added `Playerbot` tag but it is unclear if the issue is really related to bots or if this is a broader issue that also affects bots following their master.

There seems to be a similar issue if you're doing escorts. If you escort an NPC that hit's a point where it spawns some adds with your Bot nearby there's a chance, if your bot tries to attack a killed NPC that starts to vanish/despawn on kill, to crash the core. 

I don't know if I should open up an extra issue for it but it happened now with some random selected escorts but only with a Bot nearby so I think it's something in their pathing?

**Comment by cyberium** [comment]
iam not able to reproduce this anymore. Maybe someone here can confirm it work now??
Lot of change have been done in recast and pathfinding code.
