### ISSUE TITLE
🐛 [Bug Report] Segfault when Setbonus is applied

### ISSUE THREAD

**Issue by d3rrial** [cmangos/issues#2369]
## 🐛 Bugreport
Segfault when equipping Hunter Dungeonset 3 (Beast Lord)

The Server Segfaults when the 4-piece Setbonus of the dungeon set (itemset 650) is applied to the player/pet (SpellID 37483) *while the pet is summoned*
If the pet is dismissed while equipping the set, everything works.
If you summon the pet having the set equipped, everything works.
If you unequip set-items and equip them again while the pet is summoned => segfault.

### Expected behavior
The Server should not Segfault when equipping an itemset.

### Version & Environment

Client Version: 2.4.3

CMaNGOS Repo & Commit Hash: db80f324f0b39492e74fe864f502e9b7caf9555b

Database Repo & Commit Hash: ea679ee148f7556515c89e77daaacd4ed4662ccb

Operating System: Linux hostname 5.10.5-arch1-1 #1 SMP PREEMPT Thu, 07 Jan 2021 09:50:43 +0000 x86_64 GNU/Linux

### Steps to reproduce
1. Create Hunter
2. Make Hunter Level 70
2.5. Tame/Summon a Pet
3. Equip Itemset 650
4. ...
5. Profit

### Crashlog

- Will follow soon, need to recompile with debug options

Edit:
I don't know how to get a proper crashlog out of gdb,
it crashes in this file at this line: [...]/src/game/Spells/SpellAuras.h:432
```cpp
Unit* GetCaster() const { return GetHolder()->GetCaster(); }
```

backtrace gives me this:

```
#0  0x000055fd42449c04 in SpellAuraHolder::GetCaster (this=0x2000000020001) at /home/mangos/mangos/src/game/Spells/SpellAuras.cpp:8357
#1  0x000055fd4214ee42 in Aura::GetCaster (this=0x7fc5140008d0) at /home/mangos/mangos/src/game/Spells/SpellAuras.h:432
#2  0x000055fd42430255 in Aura::UpdateAuraScaling (this=0x7fc5140008d0) at /home/mangos/mangos/src/game/Spells/SpellAuras.cpp:846
#3  0x000055fd4214c611 in Unit::UpdateScalingAuras (this=0x7fc50b083b90) at /home/mangos/mangos/src/game/Entities/Unit.cpp:12283
#4  0x000055fd42105a75 in Player::UpdateStats (this=0x7fc50a277940, stat=STAT_STAMINA) at /home/mangos/mangos/src/game/Entities/StatSystem.cpp:46
#5  0x000055fd42140f96 in Unit::HandleStatModifier (this=0x7fc50a277940, unitMod=UNIT_MOD_STAT_STAMINA, modifierType=BASE_VALUE, amount=21, apply=true) at /home/mangos/mangos/src/game/Entities/Unit.cpp:9276
#6  0x000055fd4209c353 in Player::_ApplyItemBonuses (this=0x7fc50a277940, proto=0x7fc531079ca4, slot=0 '\000', apply=true) at /home/mangos/mangos/src/game/Entities/Player.cpp:7304
#7  0x000055fd4209c08e in Player::_ApplyItemMods (this=0x7fc50a277940, item=0x7fc50af147d0, slot=0 '\000', apply=true) at /home/mangos/mangos/src/game/Entities/Player.cpp:7253
#8  0x000055fd420a5110 in Player::EquipItem (this=0x7fc50a277940, pos=65280, pItem=0x7fc50af147d0, update=true) at /home/mangos/mangos/src/game/Entities/Player.cpp:10508
#9  0x000055fd425abb0a in WorldSession::HandleAutoEquipItemOpcode (this=0x7fc4f0001970, recv_data=...) at /home/mangos/mangos/src/game/Entities/ItemHandler.cpp:221
#10 0x000055fd423e17d3 in WorldSession::ExecuteOpcode (this=0x7fc4f0001970, opHandle=..., packet=...) at /home/mangos/mangos/src/game/Server/WorldSession.cpp:1132
#11 0x000055fd423de64d in WorldSession::Update (this=0x7fc4f0001970, diff=50) at /home/mangos/mangos/src/game/Server/WorldSession.cpp:374
#12 0x000055fd424c6685 in World::UpdateSessions (this=0x55fd43d52510, diff=50) at /home/mangos/mangos/src/game/World/World.cpp:2052
#13 0x000055fd424c3b48 in World::Update (this=0x55fd43d52510, diff=50) at /home/mangos/mangos/src/game/World/World.cpp:1511
#14 0x000055fd41eefac1 in WorldRunnable::run (this=0x55fd598198d0) at /home/mangos/mangos/src/mangosd/WorldRunnable.cpp:58
#15 0x000055fd41f33e97 in MaNGOS::Thread::ThreadTask (param=0x55fd598198d0) at /home/mangos/mangos/src/shared/Threading.cpp:84
#16 0x000055fd41f34dd6 in std::__invoke_impl<void, void (*)(void*), void*> (__f=@0x55fd59819f70: 0x55fd41f33e6c <MaNGOS::Thread::ThreadTask(void*)>) at /usr/include/c++/10.2.0/bits/invoke.h:60
#17 0x000055fd41f34d4b in std::__invoke<void (*)(void*), void*> (__fn=@0x55fd59819f70: 0x55fd41f33e6c <MaNGOS::Thread::ThreadTask(void*)>) at /usr/include/c++/10.2.0/bits/invoke.h:95
#18 0x000055fd41f34cbb in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::_M_invoke<0ul, 1ul> (this=0x55fd59819f68) at /usr/include/c++/10.2.0/thread:264
#19 0x000055fd41f34c74 in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::operator() (this=0x55fd59819f68) at /usr/include/c++/10.2.0/thread:271
#20 0x000055fd41f34c58 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(void*), void*> > >::_M_run (this=0x55fd59819f60) at /usr/include/c++/10.2.0/thread:215
#21 0x00007fc535347c24 in std::execute_native_thread_routine (__p=0x55fd59819f60) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#22 0x00007fc53583e3e9 in start_thread () from /usr/lib/libpthread.so.0
#23 0x00007fc53504f293 in clone () from /usr/lib/libc.so.6
```

bt full gives this:
```
#0  0x000055fd42449c04 in SpellAuraHolder::GetCaster (this=0x2000000020001) at /home/mangos/mangos/src/game/Spells/SpellAuras.cpp:8357
No locals.
#1  0x000055fd4214ee42 in Aura::GetCaster (this=0x7fc5140008d0) at /home/mangos/mangos/src/game/Spells/SpellAuras.h:432
No locals.
#2  0x000055fd42430255 in Aura::UpdateAuraScaling (this=0x7fc5140008d0) at /home/mangos/mangos/src/game/Spells/SpellAuras.cpp:846
        caster = 0x7fc507966708
#3  0x000055fd4214c611 in Unit::UpdateScalingAuras (this=0x7fc50b083b90) at /home/mangos/mangos/src/game/Entities/Unit.cpp:12283
        aura = 0x7fc5140008d0
        __for_range = std::vector of length 17, capacity 32 = {0x7fc50b0943b0, 0x7fc50b094a60, 0x7fc50b094ac0, 0x7fc50b094b20, 0x7fc50b095110, 0x7fc50b095170, 0x7fc50b0943b0, 0x7fc50b0943b0, 0x7fc50b0943b0, 0x7fc50b0943b0, 0x7fc50b0943b0, 0x7fc50b0943b0, 0x7fc50b0943b0,
          0x7fc50b0951d0, 0x7fc50b094410, 0x7fc50b094470, 0x7fc50b0943b0}
        __for_begin = 0x7fc5140008d0
        __for_end = 0x4270e8f045361c0a
#4  0x000055fd42105a75 in Player::UpdateStats (this=0x7fc50a277940, stat=STAT_STAMINA) at /home/mangos/mangos/src/game/Entities/StatSystem.cpp:46
        pet = 0x7fc50b083b90
        value = 275
        oldValue = 254
#5  0x000055fd42140f96 in Unit::HandleStatModifier (this=0x7fc50a277940, unitMod=UNIT_MOD_STAT_STAMINA, modifierType=BASE_VALUE, amount=21, apply=true) at /home/mangos/mangos/src/game/Entities/Unit.cpp:9276
        val = 3.04936559e-41
#6  0x000055fd4209c353 in Player::_ApplyItemBonuses (this=0x7fc50a277940, proto=0x7fc531079ca4, slot=0 '\000', apply=true) at /home/mangos/mangos/src/game/Entities/Player.cpp:7304
        val = 21
        i = 1
        armor = 21760
#7  0x000055fd4209c08e in Player::_ApplyItemMods (this=0x7fc50a277940, item=0x7fc50af147d0, slot=0 '\000', apply=true) at /home/mangos/mangos/src/game/Entities/Player.cpp:7253
        proto = 0x7fc531079ca4
        attacktype = 3
#8  0x000055fd420a5110 in Player::EquipItem (this=0x7fc50a277940, pos=65280, pItem=0x7fc50af147d0, update=true) at /home/mangos/mangos/src/game/Entities/Player.cpp:10508
        pProto = 0x7fc531079ca4
        bag = 255 '\377'
        slot = 0 '\000'
        pItem2 = 0x0
#9  0x000055fd425abb0a in WorldSession::HandleAutoEquipItemOpcode (this=0x7fc4f0001970, recv_data=...) at /home/mangos/mangos/src/game/Entities/ItemHandler.cpp:221
        dstbag = 255 '\377'
        dstslot = 0 '\000'
        sSrc = std::vector of length 1, capacity 1 = {{pos = 4886, count = 1 '\001'}}
        eSrc = 0
        srcbag = 19 '\023'
        srcslot = 22 '\026'
        pSrcItem = 0x7fc50af147d0
        dest = 65280
        msg = EQUIP_ERR_OK
        src = 4886
        pDstItem = 0x7fc4f8003c50
#10 0x000055fd423e17d3 in WorldSession::ExecuteOpcode (this=0x7fc4f0001970, opHandle=..., packet=...) at /home/mangos/mangos/src/game/Server/WorldSession.cpp:1132
No locals.
#11 0x000055fd423de64d in WorldSession::Update (this=0x7fc4f0001970, diff=50) at /home/mangos/mangos/src/game/Server/WorldSession.cpp:374
        packet = std::unique_ptr<WorldPacket> = {get() = 0x7fc4f0002b70}
        opHandle = @0x55fd43016f20: {name = 0x55fd42ae59e6 "CMSG_AUTOEQUIP_ITEM", status = STATUS_LOGGEDIN, packetProcessing = PROCESS_THREADUNSAFE, handler = (void (WorldSession::*)(WorldSession * const,
    WorldPacket &)) 0x55fd425ab66e <WorldSession::HandleAutoEquipItemOpcode(WorldPacket&)>}
        recvQueueCopy = std::deque with 0 elements
#12 0x000055fd424c6685 in World::UpdateSessions (this=0x55fd43d52510, diff=50) at /home/mangos/mangos/src/game/World/World.cpp:2052
        pSession = 0x7fc4f0001970
        itr = {<std::__detail::_Node_iterator_base<std::pair<unsigned int const, WorldSession*>, false>> = {_M_cur = 0x7fc514a2e530}, <No data fields>}
#13 0x000055fd424c3b48 in World::Update (this=0x55fd43d52510, diff=50) at /home/mangos/mangos/src/game/World/World.cpp:1511
        preSessionTime = {__d = {__r = 1610877009485}}
        preMapTime = {__d = {__r = 1610877009435}}
        postMapTime = {__d = {__r = 140484212583352}}
        postSingletonTime = {__d = {__r = 140484212583360}}
        updateEndTime = {__d = {__r = 140484212583376}}
        total = 0
        presession = -6206624192566142464
        premap = 140484212583408
        map = 94546221068739
        singletons = 0
        cleanup = 140484212583440
        meas = {_vptr.measurement = 0x7fc507966c68,
          m_name = "\216\364\000\000\000\000\000\000\000ڿS.\244ݩ\240l\226\a\305\177\000\000\373\355\361A\375U\000\000\260l\226\a\305\177\000\000\340l\226\a\305\177\000\000\360l\226\a\305\177\000\000\340\306\361A\375U\000\000\000m\226\a\305\177\000\000\021\064\376\370\275n\002\000\021
\064\376\370\275n\002\000\266)Xe\257n\002\000 =\002C\375U\000\000$=\002C\375U\000\000\216\364\000\000\000\000\000\000\000ڿS.\244ݩ\000m\226\a\305\177\000\000l>\363A\375U\000\000\060m\226\a\305\177\000\000\301\372\356A\375U\000\000\000\000\000\000\000\000\000\000И\201Y\375U\000\000\062
\000\000\000\216\364\000\000\\\364\000\000\062\000\000\000`m\226\a\305\177\000\000"..., m_tags = std::map with 140484212583584 elements<error reading variable: Cannot access memory at address 0xf4a6>,
          m_fields = std::map with 140484212583680 elements<error reading variable: Cannot access memory at address 0x83fc452bf0458b29>, m_timestamp = {__d = {__r = 684712158704657}},
          m_condition = {<std::_Maybe_unary_or_binary_function<bool>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8, _M_functor = {_M_unused = {_M_object = 0x26ebdf8fe3411, _M_const_object = 0x26ebdf8fe3411,
                  _M_function_pointer = 0x26ebdf8fe3411, _M_member_pointer = &virtual table offset 684712158704656, this adjustment 684649552030134}, _M_pod_data = "\021\064\376\370\275n\002\000\266)Xe\257n\002"}, _M_manager = 0x55fd43023d20 <WorldTimer::m_iTime>},
            _M_invoker = 0x55fd43023d24 <WorldTimer::m_iPrevTime>}}
#14 0x000055fd41eefac1 in WorldRunnable::run (this=0x55fd598198d0) at /home/mangos/mangos/src/mangosd/WorldRunnable.cpp:58
        diff = 50
        realCurrTime = 62606
        realPrevTime = 62556
        prevSleepTime = 50
#15 0x000055fd41f33e97 in MaNGOS::Thread::ThreadTask (param=0x55fd598198d0) at /home/mangos/mangos/src/shared/Threading.cpp:84
        _task = 0x55fd598198d0
#16 0x000055fd41f34dd6 in std::__invoke_impl<void, void (*)(void*), void*> (__f=@0x55fd59819f70: 0x55fd41f33e6c <MaNGOS::Thread::ThreadTask(void*)>) at /usr/include/c++/10.2.0/bits/invoke.h:60
No locals.
#17 0x000055fd41f34d4b in std::__invoke<void (*)(void*), void*> (__fn=@0x55fd59819f70: 0x55fd41f33e6c <MaNGOS::Thread::ThreadTask(void*)>) at /usr/include/c++/10.2.0/bits/invoke.h:95
No locals.
#18 0x000055fd41f34cbb in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::_M_invoke<0ul, 1ul> (this=0x55fd59819f68) at /usr/include/c++/10.2.0/thread:264
No locals.
#19 0x000055fd41f34c74 in std::thread::_Invoker<std::tuple<void (*)(void*), void*> >::operator() (this=0x55fd59819f68) at /usr/include/c++/10.2.0/thread:271
No locals.
#20 0x000055fd41f34c58 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(void*), void*> > >::_M_run (this=0x55fd59819f60) at /usr/include/c++/10.2.0/thread:215
No locals.
#21 0x00007fc535347c24 in std::execute_native_thread_routine (__p=0x55fd59819f60) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
        __t = std::unique_ptr<std::thread::_State> = {get() = <optimized out>}
#22 0x00007fc53583e3e9 in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#23 0x00007fc53504f293 in clone () from /usr/lib/libc.so.6
No symbol table info available.
```

The offending aura looks like this in gdb:
```
$13 = {_vptr.Aura = 0x5000500030005, m_modifier = {m_auraname = 458752, m_amount = 65542, m_miscvalue = 262145, periodictime = 1, m_recentAmount = 65537, m_baseAmount = 0}, m_spellmod = 0x1000400010002, m_applyTime = 281479271743489, m_currentBasePoints = 65537,
  m_periodicTimer = 65537, m_periodicTick = 65537, m_removeMode = AURA_REMOVE_BY_STACK, m_effIndex = EFFECT_INDEX_0, m_positive = false, m_isPeriodic = false, m_isAreaAura = false, m_isPersistent = false, m_magnetUsed = false, m_spellAuraHolder = 0x2000000020001,
  m_scriptValue = 281479272005633}
```
as you can see, `m_spellAuraHolder` is an invalid pointer, but I don't know how it got there

**Comment by killerwife** [comment]
Fixed in latest commit on tbc+.
