### ISSUE TITLE
Segfault when issuing a reload command via console

### ISSUE THREAD

**Issue by idl0r** [cmangos/issues#528]
Example of a "reload all" via console:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to LWP 23792]
0x000005f029b2ff0c in WorldSession::GetPlayer (this=0x0) at /home/wow/cmangos-tbc-repo/src/game/WorldSession.h:171
171             Player* GetPlayer() const { return _player; }
(gdb) bt
#0  0x000005f029b2ff0c in WorldSession::GetPlayer (this=0x0) at /home/wow/cmangos-tbc-repo/src/game/WorldSession.h:171
#1  0x000005f029ead130 in ChatHandler::SendGlobalSysMessage (this=0x739534161de0, str=0x5f02a207bc8 "DB table `skill_fishing_base_level` (fishing base level for zone/subzone) reloaded.") at /home/wow/cmangos-tbc-repo/src/game/Chat.cpp:949
#2  0x000005f029b46665 in ChatHandler::HandleReloadSkillFishingBaseLevelCommand (this=0x739534161de0) at /home/wow/cmangos-tbc-repo/src/game/Level3.cpp:667
#3  0x000005f029b44ad7 in ChatHandler::HandleReloadAllCommand (this=0x739534161de0) at /home/wow/cmangos-tbc-repo/src/game/Level3.cpp:230
#4  0x000005f029eaddf5 in ChatHandler::ExecuteCommand (this=0x739534161de0, text=0x739533853ffa "") at /home/wow/cmangos-tbc-repo/src/game/Chat.cpp:1193
#5  0x000005f029eae429 in ChatHandler::ParseCommands (this=0x739534161de0, text=0x739533853ff0 "reload all") at /home/wow/cmangos-tbc-repo/src/game/Chat.cpp:1309
#6  0x000005f02a0224d4 in World::ProcessCliCommands (this=0x739550153900) at /home/wow/cmangos-tbc-repo/src/game/World.cpp:1931
#7  0x000005f02a020e38 in World::Update (this=0x739550153900, diff=50) at /home/wow/cmangos-tbc-repo/src/game/World.cpp:1555
#8  0x000005f029afe229 in WorldRunnable::run (this=0x7395339154a0) at /home/wow/cmangos-tbc-repo/src/mangosd/WorldRunnable.cpp:59
#9  0x000005f02a12b8af in ACE_Based::Thread::ThreadTask (param=0x7395339154a0) at /home/wow/cmangos-tbc-repo/src/shared/Threading.cpp:186
#10 0x000073954dd241da in ?? ()
#11 0x0000000000000000 in ?? ()
```

So a first draft/proposal would be:
```
From 529678e3d3c51ca234b8a21f9d55ff4d31201ba1 Mon Sep 17 00:00:00 2001
From: Christian Ruppert <idl0r@qasl.de>
Date: Sun, 7 Dec 2014 14:00:25 +0100
Subject: [PATCH] Fix segfault when issuing a reload command via console

Issuing a reload command will usually broadcast a global chat/system message
with the player as sender. When doing that via console there is no actual player
and thus m_session is NULL.
---
 src/game/Chat.cpp | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/src/game/Chat.cpp b/src/game/Chat.cpp
index 48b9bd3..07ee90d 100644
--- a/src/game/Chat.cpp
+++ b/src/game/Chat.cpp
@@ -937,6 +937,10 @@ void ChatHandler::SendSysMessage(const char* str)

 void ChatHandler::SendGlobalSysMessage(const char* str)
 {
+    // Check if initiated via console
+    if(!m_session)
+        return;
+
     // Chat output
     WorldPacket data;

--
2.0.4
```

It must be verified whether other versions are affected as well or not. This was tested with TBC.

**Comment by Schmoozerd** [comment]
Thanks very much for reporting!
