### ISSUE TITLE
Crash on Pet Aura Update

### ISSUE THREAD

**Issue by ryancheung** [cmangos/issues#887]
**Current behavior**: 
Crash
**Expected behavior**: 
Normal
**Steps to reproduce**:
Unknown
**Client version**: 
1.12.1
**Commit hash**: 
5a2a1b8809d11396227f2dc6ac21aa206bc5432f
**Database version**: 

**Operating system**: 
Ubuntu 14.04 LTS

[//]: # (If this is a crash report, include the crashlog from a debug build with https://gist.github.com/)
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe5f66700 (LWP 2531)]
0x0000000000cbca79 in Aura::UpdateAura (this=0x7fff7e4ae530, diff=150) at /home/ubuntu/mangos/server/src/game/WorldHandlers/SpellAuras.h:457
457     /home/ubuntu/mangos/server/src/game/WorldHandlers/SpellAuras.h: No such file or directory.
(gdb) bt
#0  0x0000000000cbca79 in Aura::UpdateAura (this=0x7fff7e4ae530, diff=150) at /home/ubuntu/mangos/server/src/game/WorldHandlers/SpellAuras.h:457
#1  0x0000000000cbba84 in SpellAuraHolder::Update (this=0x7fff67481700, diff=150) at /home/ubuntu/mangos/server/src/game/WorldHandlers/SpellAuras.cpp:5465
#2  0x0000000000adb4f3 in SpellAuraHolder::UpdateHolder (this=0x7fff67481700, diff=150) at /home/ubuntu/mangos/server/src/game/WorldHandlers/SpellAuras.h:154
#3  0x0000000000ac431d in Unit::_UpdateSpells (this=0x7fffdc4d56a0, time=150) at /home/ubuntu/mangos/server/src/game/Object/Unit.cpp:2985
#4  0x0000000000aba31c in Unit::Update (this=0x7fffdc4d56a0, update_diff=150, p_time=150) at /home/ubuntu/mangos/server/src/game/Object/Unit.cpp:325
#5  0x0000000000b2cba0 in Creature::Update (this=0x7fffdc4d56a0, update_diff=150, diff=150) at /home/ubuntu/mangos/server/src/game/Object/Creature.cpp:606
#6  0x0000000000af5651 in Pet::Update (this=0x7fffdc4d56a0, update_diff=150, diff=150) at /home/ubuntu/mangos/server/src/game/Object/Pet.cpp:630
#7  0x0000000000d51fb3 in WorldObject::UpdateHelper::Update (this=0x7fffe5f64b60, time_diff=150) at /home/ubuntu/mangos/server/src/game/Object/Object.h:524
#8  0x0000000000d71345 in MaNGOS::ObjectUpdater::Visit (this=0x7fffe5f64d10, m=...) at /home/ubuntu/mangos/server/src/game/WorldHandlers/GridNotifiersImpl.h:54
#9  0x0000000000d7f6ef in VisitorHelper<MaNGOS::ObjectUpdater, Creature> (v=..., c=...) at /home/ubuntu/mangos/server/src/framework/GameSystem/TypeContainerVisitor.h:72
#10 0x0000000000d7f1db in VisitorHelper<MaNGOS::ObjectUpdater, Creature, TypeList<Corpse, TypeList<Camera, TypeNull> > > (v=..., c=...)
    at /home/ubuntu/mangos/server/src/framework/GameSystem/TypeContainerVisitor.h:85
#11 0x0000000000d7e9e0 in VisitorHelper<MaNGOS::ObjectUpdater, Player, TypeList<Creature, TypeList<Corpse, TypeList<Camera, TypeNull> > > > (v=..., c=...)
    at /home/ubuntu/mangos/server/src/framework/GameSystem/TypeContainerVisitor.h:86
#12 0x0000000000d7dd18 in VisitorHelper<MaNGOS::ObjectUpdater, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<Camera, TypeNull> > > > > (v=..., c=...)
    at /home/ubuntu/mangos/server/src/framework/GameSystem/TypeContainerVisitor.h:98
#13 0x0000000000d7cc1a in TypeContainerVisitor<MaNGOS::ObjectUpdater, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<Camera, TypeNull> > > > > >::V---Type <return> to continue, or q <return> to quit---
isit (this=0x7fffe5f64d50, c=...) at /home/ubuntu/mangos/server/src/framework/GameSystem/TypeContainerVisitor.h:127
#14 0x0000000000d7ad30 in Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<Camera, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::Visit<MaNGOS::ObjectUpdater> (this=0x7fff5d599170, visitor=...) at /home/ubuntu/mangos/server/src/framework/GameSystem/Grid.h:111
#15 0x0000000000d78320 in NGrid<16u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<Camera, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::Visit<MaNGOS::ObjectUpdater, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<Camera, TypeNull> > > > > (
    this=0x7fff5d592660, x=@0x7fffe5f64ca0: 3, y=@0x7fffe5f64ca4: 13, visitor=...) at /home/ubuntu/mangos/server/src/framework/GameSystem/NGrid.h:360
#16 0x0000000000d739b0 in Map::Visit<MaNGOS::ObjectUpdater, TypeMapContainer<TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<Camera, TypeNull> > > > > > (
    this=0x65f90f0, cell=..., visitor=...) at /home/ubuntu/mangos/server/src/game/WorldHandlers/Map.h:469
#17 0x0000000000d689f2 in Map::Update (this=0x65f90f0, t_diff=@0x7fff9a9e8d50: 150) at /home/ubuntu/mangos/server/src/game/WorldHandlers/Map.cpp:528
#18 0x0000000000e48042 in MapUpdateRequest::call (this=0x7fff9a9e8d30) at /home/ubuntu/mangos/server/src/game/Maps/MapUpdater.cpp:78
#19 0x0000000000ebb83b in DelayExecutor::svc (this=0x65879a0) at /home/ubuntu/mangos/server/src/shared/Threading/DelayExecutor.cpp:76
#20 0x00007ffff7757af7 in ACE_Task_Base::svc_run(void*) () from /mangos/lib/libace.so
#21 0x00007ffff77591e5 in ACE_Thread_Adapter::invoke_i() () from /mangos/lib/libace.so
#22 0x00007ffff775912f in ACE_Thread_Adapter::invoke() () from /mangos/lib/libace.so
#23 0x00007ffff5e4e182 in start_thread (arg=0x7fffe5f66700) at pthread_create.c:312
#24 0x00007ffff5b7b47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by Phatcat** [comment]
I can see you reported this crash in april; several weeks after ace was removed, however I note this in the call stack:
> #20 0x00007ffff7757af7 in ACE_Task_Base::svc_run(void*) () from /mangos/lib/libace.so
#21 0x00007ffff77591e5 in ACE_Thread_Adapter::invoke_i() () from /mangos/lib/libace.so
#22 0x00007ffff775912f in ACE_Thread_Adapter::invoke() () from /mangos/lib/libace.so

So this was either a custom core or not a core that was up to date; since noone else is reporting any crashes related to pets and auras I am going to close this, at least for now.
